### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AsyncFunctionDef'

### ISSUE THREAD

**Issue by puterleat** [azazel75/metapensiero.pj#4]
Created a simple test.py containing

    print(2+2)

Then run with

python3 -m metapensiero.pj test.py

And get

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/metapensiero/pj/__main__.py", line 13, in <module>
    from . import api
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/metapensiero/pj/api.py", line 16, in <module>
    from .processor.transforming import Transformer
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/metapensiero/pj/processor/transforming.py", line 19, in <module>
    from .util import (rfilter, parent_of, random_token, Line, Part, obj_source,
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/metapensiero/pj/processor/util.py", line 59, in <module>
    ast.AsyncFunctionDef)
AttributeError: 'module' object has no attribute 'AsyncFunctionDef'
```

**Comment by puterleat** [comment]
btw:

```
python3 --version
Python 3.4.3
```

**Comment by azazel75** [comment]
The Python used it's supposed to be the 3.5 version.. Maybe I should make it more clear
